---
abstract: 'Memcached-based session backend for Dancer'
author:
  - 'Alexis Sukrieh <surkia@sukria.net>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Memcached
requires:
  Cache::Memcached: 0
  Dancer::Config: 0
  Dancer::ModuleLoader: 0
  Dancer::Session::Abstract: 0
resources:
  repository: http://github.com/sukria/Dancer-Session-Memcached
version: 0.201
